export const FILTER_INCOMES_CATEGORY = 'FILTER_INCOMES_CATEGORY';
export const FILTER_INCOMES_TOTAL = 'FILTER_INCOMES_TOTAL';
export const FILTER_INCOMES_DATE = 'FILTER_INCOMES_DATE';
export const ADD_CATEGORY='ADD_CATEGORY'